name: curebay_app
description: An offline-first medical triage mobile application using Flutter, ONNX models, SQLite, and Vosk for speech-to-text.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  provider: ^6.1.1
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  printing: ^5.11.1
  pdf: ^3.10.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add assets like models
  assets:
    - assets/xgboost_disease_model.onnx
