import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import 'dart:convert';

class ReferralCard extends StatelessWidget {
  final String patientName;
  final int age;
  final String gender;
  final String topDiagnosis;
  final double confidence;
  final String riskLevel;
  final List<String> symptoms;
  final Map<String, dynamic> vitals;

  const ReferralCard({
    Key? key,
    required this.patientName,
    required this.age,
    required this.gender,
    required this.topDiagnosis,
    required this.confidence,
    required this.riskLevel,
    required this.symptoms,
    required this.vitals,
  }) : super(key: key);

  String _buildReferralText() {
    return '''
CUREBAY REFERRAL NOTE
======================
Patient: $patientName
Age: $age | Gender: $gender

Vitals:
  Temp: ${vitals['Temperature']}°C
  BP: ${vitals['SysBP']}/${vitals['DiaBP']} mmHg
  SpO2: ${vitals['SpO2']}%
  HR: ${vitals['HeartRate']} BPM

Reported Symptoms:
  ${symptoms.map((s) => s.replaceAll('_', ' ')).join(', ')}

Primary Diagnosis: $topDiagnosis (${(confidence * 100).toStringAsFixed(1)}%)
Risk Level: $riskLevel

Please conduct confirmatory diagnostics.
Generated by Curebay App.
''';
  }

  String _buildQrData() {
    return jsonEncode({
      'patient': patientName,
      'age': age,
      'gender': gender,
      'diagnosis': topDiagnosis,
      'confidence': confidence,
      'risk': riskLevel,
      'symptoms': symptoms,
      'vitals': vitals,
      'timestamp': DateTime.now().toIso8601String(),
    });
  }

  @override
  Widget build(BuildContext context) {
    final riskColor = riskLevel == 'Emergency'
        ? Colors.red
        : riskLevel == 'Urgent'
            ? Colors.orange
            : Colors.green;

    return Card(
      elevation: 4,
      margin: const EdgeInsets.all(12),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Row(
              children: [
                Icon(Icons.local_hospital, color: riskColor, size: 28),
                const SizedBox(width: 8),
                const Text('Referral Note',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                const Spacer(),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: riskColor.withOpacity(0.15),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(
                    riskLevel.toUpperCase(),
                    style: TextStyle(
                        color: riskColor, fontWeight: FontWeight.bold, fontSize: 12),
                  ),
                ),
              ],
            ),
            const Divider(height: 24),

            // Patient summary
            Text('Patient: $patientName  |  Age: $age  |  $gender',
                style: const TextStyle(fontSize: 14)),
            const SizedBox(height: 8),
            Text('Primary Diagnosis: $topDiagnosis  (${(confidence * 100).toStringAsFixed(1)}%)',
                style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w600)),
            const SizedBox(height: 16),

            // QR Code
            Center(
              child: QrImageView(
                data: _buildQrData(),
                version: QrVersions.auto,
                size: 160.0,
                gapless: false,
              ),
            ),
            const SizedBox(height: 8),
            const Center(
              child: Text('Scan QR at clinic to load patient record',
                  style: TextStyle(fontSize: 11, color: Colors.grey)),
            ),
            const SizedBox(height: 16),

            // Action buttons
            Row(
              children: [
                Expanded(
                  child: ElevatedButton.icon(
                    onPressed: () {
                      Share.share(_buildReferralText(), subject: 'Curebay Referral: $patientName');
                    },
                    icon: const Icon(Icons.share, size: 18),
                    label: const Text('Share via WhatsApp/SMS'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.teal,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 12),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
